<?php

$plugin = array(
  'title' => t('header '),
  'category' => t('Republish layouts'),
  'icon' => 'head.png',
  'theme' => 'head',
  'css' => 'head.css',
  'regions' => array(
    'logo' => t('Logo'),
    'mobile_menu' => t('Mobile-menu'),
    'main_menu' => t('Main-menu'),
      'favorite' => t('Favorite'),
      'mega_menu' => t('Mega-menu'),
    'sub_mega_menu' => t('Sub Mega-menu'),
    'sub_menu' => t('Sub-menu'),
    'buttons' => t('Buttons'),
  ),
);
