<?php

$plugin = array(
  'title' => t('Two Columns 3/4 + 1/4'),
  'category' => t('Republish layouts'),
  'icon' => 'towcol_25_75.png',
  'theme' => 'twocol_25_75',
  'css' => 'twocol_25_75.css',
  'regions' => array(
    'header' => t('Header'),
    'main_right' => t('Main-Right'),
    'main_left' => t('Main-Left'),
    'banner_main' => t('Banner-main'),
    'sub_right' => t('Sub-right'),
    'sub_left' => t('Sub-left'),
  ),
);
