version: '2'

services:
    web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - "./src:/code"
          - "./site.conf:/etc/nginx/conf.d/default.conf"
    php:
      image: php:fpm
      volumes:
          - "./src:/code"

    mysql:
      image: "mariadb"
      container_name: "republish-db"
      environment:
        MYSQL_ROOT_PASSWORD: "newstart"
        MYSQL_DATABASE: republish
      volumes:
        - "./data/mysql:/var/lib/mysql"

