<?php

/**
 * Define module constants.
 */

// Constants for rich snippets support.
define('rp_breadcrumbs_RICH_SNIPPETS_DISABLED', 0);
define('rp_breadcrumbs_RICH_SNIPPETS_RDFA', 1);
define('rp_breadcrumbs_RICH_SNIPPETS_MICRODATA', 2);

// Constant for cache storage.
define('rp_breadcrumbs_CACHE_STORAGE', 'cache_rp_breadcrumbs');

/**
 * Init Path Breadcrumbs.
 */
function rp_breadcrumbs_set_breadcrumb($path = NULL) {
  if (!isset($path)) {
    $path = current_path();
  }

  // See if current page has path breadcrumbs.
  $rp_breadcrumbs_data = rp_breadcrumbs_load_variant($path);

  // Set breadcrumbs for current page if it exists.
  if ($rp_breadcrumbs_data && isset($rp_breadcrumbs_data->build)) {
    drupal_set_breadcrumb($rp_breadcrumbs_data->build);
  }
}

/**
 * Load and build path breadcrumb variant for page url. Results are cached.
 *
 * @param string $path
 *   Current page url.
 *
 * @return object
 *   Path breadcrumb object that matches page url.
 *   Members:
 *    - variant: raw Path Breadcrumbs variant;
 *    - build: built Path Breadcrumbs array ready for drupal_set_breadcrumb().
 */
function rp_breadcrumbs_load_variant($path) {
  global $language_url;

  if (empty($path)) {
    return FALSE;
  }

  $rp_breadcrumbs_data = &drupal_static(__FUNCTION__ . '::' . $path);
  if (!empty($rp_breadcrumbs_data)) {
    return $rp_breadcrumbs_data;
  }

  // See if user enabled cache for breadcrumbs.
  $cache_enabled = variable_get('rp_breadcrumbs_cache_enabled', FALSE);
  $cache_lifetime = variable_get('rp_breadcrumbs_cache_lifetime', CACHE_PERMANENT);
  // Apply current time to cache expiration time to set valid cache expire date.
  if ($cache_lifetime > CACHE_PERMANENT) {
    $cache_lifetime += REQUEST_TIME;
  }

  if ($cache_enabled) {
    // Trying to load breadcrumb from cache.
    $cache_id = __FUNCTION__ . ':' . $path . ':' . $language_url->language;
    $cache = cache_get($cache_id, rp_breadcrumbs_CACHE_STORAGE);
    if (!empty($cache->data)) {
      // Empty results are also cached.
      if ($cache->data == 'none') {
        return FALSE;
      }

      // Allow to alter cached items.
      if (count(module_implements('rp_breadcrumbs_view_alter')) > 0) {
        $built_breadcrumbs = $cache->data->build;
        $rp_breadcrumbs = $cache->data->variant;
        $rp_breadcrumbs->from_cache = TRUE;
        $contexts = rp_breadcrumbs_get_contexts_from_arguments($rp_breadcrumbs->arguments, FALSE, $path);
        drupal_alter('rp_breadcrumbs_view', $built_breadcrumbs, $rp_breadcrumbs, $contexts);
      }

      // Store data in static cache.
      $rp_breadcrumbs_data = $cache->data;

      return $cache->data;
    }
  }

  $rp_breadcrumbs_data = new stdClass();

  // Select all variants matching current path.
  $variants = rp_breadcrumbs_load_by_path($path);

  // Check if current path maches variant.
  // When first variant is found - return it.
  foreach ($variants as $breadcrumb) {

    // Replace placeholder in path with '*'.
    // Example: 'node/%node/view' -> 'node/*/view'.
    $matched_path = preg_replace("
        /\/%    # start with slash-percent
        [^\/]+  # all symbols except for the slash
        /x", '/*', $breadcrumb->path);

    if (drupal_match_path($path, $matched_path)) {

      // Load breadcrumbs' contexts from current path.
      $contexts = rp_breadcrumbs_get_contexts_from_arguments($breadcrumb->arguments, FALSE, $path);

      // If breadcrumb contains broken context
      // it means that unable to load context from URL.
      if (isset($contexts['broken_context'])) {
        continue;
      }

      // Check if breadcrumb is accessable for current page.
      if (!empty($breadcrumb->access)) {
        $access = ctools_access($breadcrumb->access, $contexts);
        if (!$access) {
          continue;
        }
      }

      // Appropriate variant found.
      $rp_breadcrumbs_data->variant = $breadcrumb;
      // Build suitable breadcrumb variant.
      $rp_breadcrumbs_data->build = _rp_breadcrumbs_build_breadcrumbs($breadcrumb, $contexts);

      // Save data in cache and return it.
      if ($cache_enabled) {
        cache_set($cache_id, $rp_breadcrumbs_data, rp_breadcrumbs_CACHE_STORAGE, $cache_lifetime);
      }

      return $rp_breadcrumbs_data;
    }

  }

  // Save empty data in cache and return it.
  if ($cache_enabled) {
    cache_set($cache_id, 'none', rp_breadcrumbs_CACHE_STORAGE, $cache_lifetime);
  }

  return FALSE;
}

/**
 * Build breadcrumbs navigation from loaded path breadcrumb variant.
 *
 * @param object $path_breadcrumb
 *   Object with path breadcrumb variant loaded from database.
 * @param array $contexts
 *   Ctools contexts from current URL.
 *
 * @return array
 *   Array with breadcrumbs navigation.
 */
function _rp_breadcrumbs_build_breadcrumbs($path_breadcrumb, $contexts = array()) {
  $breadcrumb = array();

  // Add hook_rp_breadcrumbs_view() for other developers.
  module_invoke_all('rp_breadcrumbs_view', $path_breadcrumb, $contexts);

  // Prepend HOME link to breadcrumbs navigation.
  if ($path_breadcrumb->home == TRUE) {
    $home = variable_get('rp_breadcrumbs_home_link_title', 'Home');
    $breadcrumb[] = l($home, '<front>');
  }

  // Convert breadcrumb titles and paths to string.
  $titles = implode("\n", $path_breadcrumb->titles);
  $paths  = implode("\n", $path_breadcrumb->paths);

  // Replace %nn sequences to prevent mixing them with contexts.
  $paths = rawurldecode($paths);

  // Replace module placeholders.
  $replace = array();
  $search = array();

  // Replace placeholders by its value from url.
  if (!empty($path_breadcrumb->arguments)) {
    foreach ($path_breadcrumb->arguments as $keyword => $argument) {
      $search[]  = '!' . $keyword;
      $replace[] = arg($argument['position']);
    }
  }

  // Replace placeholder for current page title.
  $search[]  = '!page_title';
  $replace[] = drupal_get_title();

  // Replace module placeholders.
  $titles = str_replace($search, $replace, $titles);
  $paths  = str_replace($search, $replace, $paths);

  // Add custom ctools context for site.
  $contexts['site'] = ctools_context_create('rp_breadcrumbs_site');

  // Replace placeholders by current context values.
  $titles = ctools_context_keyword_substitute($titles, array(), $contexts);
  $paths  = ctools_context_keyword_substitute($paths, array(), $contexts);

  // Explode titles and paths into array.
  $path_breadcrumb->titles_prepared = explode("\n", $titles);
  $path_breadcrumb->paths_prepared  = explode("\n", $paths);

  // Support empty breadcrumbs (disabling).
  if (count($path_breadcrumb->titles_prepared) == 1 &&
    $path_breadcrumb->titles_prepared[0] == '<none>' &&
    $path_breadcrumb->paths_prepared[0] == '<none>') {
    $path_breadcrumb->titles_prepared = array();
    $path_breadcrumb->paths_prepared = array();
  }

  foreach ($path_breadcrumb->titles_prepared as $key => $title) {

    // Remove breadcrumb from navigation if it is empty.
    if (empty($title)) {
      continue;
    }

    $options = array();

    // Decode title if needed.
    $decode_html_entities = variable_get('rp_breadcrumbs_decode_entities', TRUE);
    if ($decode_html_entities) {
      $title = html_entity_decode($title, ENT_QUOTES, 'UTF-8');
    }
    // Truncate to max length, consider ellipsis (+3 symbols).
    $truncate_length = variable_get('rp_breadcrumbs_truncate_title_length', '');
    $title_length = drupal_strlen($title);
    if ($truncate_length && $truncate_length < $title_length) {
      // Show full title in tooltip.
      $options['attributes']['title'] = $title;
      $title = truncate_utf8($title, $truncate_length + 3, TRUE, TRUE);
    }

    // Set a breadcrumb as a link or as a plain text.
    if (isset($path_breadcrumb->paths_prepared[$key]) && $path_breadcrumb->paths_prepared[$key] != '<none>') {
      $path = _rp_breadcrumbs_clean_url($path_breadcrumb->paths_prepared[$key], $options);
      $breadcrumb[] = l($title, $path, $options);
    }
    elseif (isset($path_breadcrumb->paths_prepared[$key]) && $path_breadcrumb->paths_prepared[$key] == '<none>') {
      $breadcrumb[] = check_plain($title);
    }
  }

  // Inform other modules that this PB item wasn't loaded from cache.
  $path_breadcrumb->from_cache = FALSE;
  // Allow other modules to alter breadcrumbs generated by this module.
  drupal_alter('rp_breadcrumbs_view', $breadcrumb, $path_breadcrumb, $contexts);

  return $breadcrumb;
}

/**
 * Implements hook_theme_registry_alter().
 */
function rp_breadcrumbs_theme_registry_alter(&$theme_registry) {
  global $theme_key;

  $internal_render = variable_get('rp_breadcrumbs_internal_render', 1);
  $themes = variable_get('rp_breadcrumbs_internal_render_themes', array());

  if ($internal_render && (empty($themes) || in_array($theme_key, $themes))) {
    $theme_registry['breadcrumb']['theme path'] = drupal_get_path('module', 'rp_breadcrumbs');
    $theme_registry['breadcrumb']['function'] = 'rp_breadcrumbs_breadcrumb';
  }
}

/**
 * Override default theme_breadcrumb().
 *
 * @param array $variables
 *   Contains array with breadcrumbs.
 *
 * @return bool|string
 *   Rendered breadcrumbs or FALSE for no breadcrumbs.
 */
function rp_breadcrumbs_breadcrumb($variables) {
  $breadcrumbs = $variables['breadcrumb'];
  if (!empty($breadcrumbs)) {

    // Provide a navigational heading to give context for breadcrumb links to
    // screen-reader users. Make the heading invisible with .element-invisible.
    $output = '<h2 class="element-invisible">' . t('You are here') . '</h2>';

    // Hide breadcrumb navigation if it contains only one element.
    $hide_single_breadcrumb = variable_get('rp_breadcrumbs_hide_single_breadcrumb', 0);
    if ($hide_single_breadcrumb && count($breadcrumbs) == 1) {
      return FALSE;
    }

    // Bootstrap 3 compatibility. See: https://drupal.org/node/2178565
    if (is_array($breadcrumbs[count($breadcrumbs) - 1])) {
      array_pop($breadcrumbs);
    }

    // Add options for rich snippets.
    $elem_tag = 'li';
    $elem_property = '';
    $root_property = '';
    $options = array('html' => TRUE);
    $snippet = variable_get('rp_breadcrumbs_rich_snippets', rp_breadcrumbs_RICH_SNIPPETS_DISABLED);
    if ($snippet == rp_breadcrumbs_RICH_SNIPPETS_RDFA) {

      // Add link options for RDFa support.
      $options['attributes'] = array('rel' => 'v:url', 'property' => 'v:title');
      $options['absolute'] = TRUE;

      // Set correct properties for RDFa support.
      $elem_property = ' typeof="v:Breadcrumb"';
      $root_property = ' xmlns:v="http://rdf.data-vocabulary.org/#"';
    }
    elseif ($snippet == rp_breadcrumbs_RICH_SNIPPETS_MICRODATA) {

      // Add link options for microdata support.
      $options['attributes'] = array('itemprop' => 'url');
      $options['absolute'] = TRUE;

      // Set correct properties for microdata support.
      $elem_property = ' itemscope itemtype="http://data-vocabulary.org/Breadcrumb"';
      $elem_tag = 'div';

      // Add style that will display breadcrumbs wrapped in <div> inline.
      drupal_add_css(drupal_get_path('module', 'rp_breadcrumbs') . '/css/rp_breadcrumbs.css');
    }

    foreach ($breadcrumbs as $key => $breadcrumb) {

      // Build classes for the breadcrumbs.
      $classes = array('inline');
      $classes[] = $key % 2 ? 'even' : 'odd';
      if ($key == 0) {
        $classes[] = 'first';
      }
      if (count($breadcrumbs) == $key + 1) {
        $classes[] = 'last';
      }

      // For rich snippets support all links should be processed in the same way,
      // even if they are provided not by Path Breadcrumbs module. So I have to
      // parse html code and create links again with new properties.
      preg_match('/href="([^"]+?)"/', $breadcrumb, $matches);

      // Remove base path from href.
      $href = '';
      if (!empty($matches[1])) {
        global $base_path;
        global $language_url;

        $base_string = rtrim($base_path, "/");

        // Append additional params to base string if clean urls are disabled.
        if (!variable_get('clean_url', 0)) {
          $base_string .= '?q=';
        }

        // Append additional params to base string for multilingual sites.
        // @note: Only core URL detection method supported.
        $enabled_negotiation_types = variable_get("language_negotiation_language", array());
        if (!empty($enabled_negotiation_types['locale-url']) && !empty($language_url->prefix)) {
          $base_string .= '/' . $language_url->prefix;
        }

        // Means that this is href to the frontpage.
        if ($matches[1] == $base_string || $matches[1] == '' || $matches[1] == '/') {
          $href = '';
        }
        // All hrefs exept frontpage.
        elseif (stripos($matches[1], "$base_string/") === 0) {
          $href = drupal_substr($matches[1], drupal_strlen("$base_string/"));
        }
        // Other cases.
        else {
          // HREF param can't starts with '/'.
          $href = stripos($matches[1], '/') === 0 ? drupal_substr($matches[1], 1) : $matches[1];
        }

        // If HREF param is empty it should be linked to a front page.
        $href = empty($href) ? '<front>' : $href;
      }

      // Get breadcrumb title from a link like "<a href = "/path">title</a>".
      $title = trim(strip_tags($breadcrumb));

      // Wrap title in additional element for microdata support.
      if ($snippet == rp_breadcrumbs_RICH_SNIPPETS_MICRODATA) {
        $title = '<span itemprop="title">' . $title . '</span>';
      }

      // Support title attribute.
      if (preg_match('/<a\s.*?title="([^"]+)"[^>]*>/i', $breadcrumb, $attr_matches)) {
        $options['attributes']['title'] = $attr_matches[1];
      }
      else {
        unset($options['attributes']['title']);
      }

      // Decode url to prevent double encoding in l().
      $href = rawurldecode($href);
      // Move query params from $href to $options.
      $href = _rp_breadcrumbs_clean_url($href, $options, 'none');

      // Build new text or link breadcrumb.
      $new_breadcrumb = !empty($href) ? l($title, $href, $options) : $title;

      // Replace old breadcrumb link with a new one.
      $breadcrumbs[$key] = '<' . $elem_tag . ' class="' . implode(' ', $classes) . '"' . $elem_property . '>' . $new_breadcrumb . '</' . $elem_tag . '>';
    }

    // Get breadcrumb delimiter and wrap it into <span> for customization.
    $delimiter = variable_get('rp_breadcrumbs_delimiter', '»');
    $delimiter = '<span class="delimiter">></span>';

    $classes = array('breadcrumb');

    // Show contextual link if it is Path Breadcrumbs variant.
    $prefix = '';
    $rp_breadcrumbs_data = rp_breadcrumbs_load_variant(current_path());
    if (user_access('administer path breadcrumbs') && $rp_breadcrumbs_data && isset($rp_breadcrumbs_data->variant)) {
      $contextual_links = array(
        '#type' => 'contextual_links',
        '#contextual_links' => array('rp_breadcrumbs' => array('admin/structure/path-breadcrumbs/edit', array($rp_breadcrumbs_data->variant->machine_name))),
      );
      $prefix = drupal_render($contextual_links);
      $classes[] = 'contextual-links-region';
    }

    // Build final version of breadcrumb's HTML output.
    $output .= '<ol class="' . implode(' ', $classes) . '"' . $root_property . '>' . $prefix . implode(" $delimiter ", $breadcrumbs) . '</ol>';

    return $output;
  }

  // Return false if no breadcrumbs.
  return FALSE;
}

/**
 * Prepare raw object from Ctools to normal rp_breadcrumbs object.
 *
 * @param object $rp_breadcrumbs_raw
 *   Object loaded from database or ctools_export_load_object().
 *
 * @return object
 *   $rp_breadcrumbs prepared object.
 */
function rp_breadcrumbs_load_prepare($rp_breadcrumbs_raw) {
  // Merge breadcrumb data with parent for more flattening structure.
  $rp_breadcrumbs = (object) array_merge((array) $rp_breadcrumbs_raw, $rp_breadcrumbs_raw->data);
  $rp_breadcrumbs->disabled = isset($rp_breadcrumbs->disabled) ? $rp_breadcrumbs->disabled : FALSE;
  $rp_breadcrumbs->is_overwritten = ($rp_breadcrumbs->export_type == (EXPORT_IN_DATABASE | EXPORT_IN_CODE));
  unset($rp_breadcrumbs->data);

  return $rp_breadcrumbs;
}

/**
 * Load path breadcrumbs by ID.
 *
 * @param int $path_id
 *   ID of path breadcrumb that should be loaded.
 *
 * @return object
 *   Loaded path breadcrumb.
 */
function rp_breadcrumbs_load($path_id) {
  // Cache it because Ctools cache is not helpful for 'conditions' loading.
  $paths = &drupal_static(__FUNCTION__);

  if (!isset($paths[$path_id])) {
    ctools_include('export');
    $result = ctools_export_load_object('rp_breadcrumbs', 'conditions', array('path_id' => $path_id));
    $rp_breadcrumbs = reset($result);
    if (!empty($rp_breadcrumbs)) {
      // Merge breadcrumb data with parent for more flattening structure.
      $rp_breadcrumbs = rp_breadcrumbs_load_prepare($rp_breadcrumbs);
      $paths[$path_id] = $rp_breadcrumbs;
    }
  }

  return isset($paths[$path_id]) ? $paths[$path_id] : FALSE;
}

/**
 * Load path breadcrumb by name.
 *
 * @param string $name
 *   Path breadcrumb's name.
 *
 * @return object
 *   Object with path breadcrumb.
 */
function rp_breadcrumbs_load_by_name($name) {
  ctools_include('export');
  $result = ctools_export_load_object('rp_breadcrumbs', 'names', array($name));

  if (!empty($result[$name])) {
    // Merge breadcrumb data with parent for more flattening structure.
    $rp_breadcrumbs = rp_breadcrumbs_load_prepare($result[$name]);
  }

  return isset($rp_breadcrumbs) ? $rp_breadcrumbs : FALSE;
}

/**
 * Load multiple objects by names.
 *
 * @param array $names
 *
 * @return array
 *   Array of path breadcrumbs objects.
 */
function rp_breadcrumbs_load_by_name_multiple($names) {
  ctools_include('export');
  $result = ctools_export_load_object('rp_breadcrumbs', 'names', $names);

  // Merge breadcrumb data with parent for more flattening structure.
  foreach ($result as $name => $rp_breadcrumbs) {
    $result[$name] = rp_breadcrumbs_load_prepare($rp_breadcrumbs);
  }

  return $result;
}

/**
 * Load all path breadcrumbs from database and code.
 *
 * @return array
 *   Array of rp_breadcrumbs objects.
 */
function rp_breadcrumbs_load_all() {

  ctools_include('export');
  $data = ctools_export_load_object('rp_breadcrumbs', 'all');

  // Make objects more developer-friendly.
  $data = array_map('rp_breadcrumbs_load_prepare', $data);

  // Order by weight.
  uasort($data, '_rp_breadcrumbs_sort_weight');
  return $data;
}

/**
 * Load enabled rp_breadcrumbs by path.
 *
 * @param string $path
 *    Current page path.
 *
 * @return array
 *    Array of rp_breadcrumbs sorted by weight.
 */
function rp_breadcrumbs_load_by_path($path) {
  $data = &drupal_static(__FUNCTION__);
  $pattern_needle = rp_breadcrumbs_path_pattern($path);

  if (empty($data[$pattern_needle])) {

    $cache = cache_get(__FUNCTION__, rp_breadcrumbs_CACHE_STORAGE);
    // Ensure the cache object has data.
    if (isset($cache->data)) {
      $data = $cache->data;
    }
    else {

      // Do heavy work and cache results.
      ctools_include('export');

      // No need to sort variants by weight because rp_breadcrumbs_load_all()
      // already sorted all data.
      $result = rp_breadcrumbs_load_all();

      foreach ($result as $rp_breadcrumbs) {
        if (empty($rp_breadcrumbs->disabled)) {
          $pattern = rp_breadcrumbs_path_pattern($rp_breadcrumbs->path);
          $data[$pattern][] = $rp_breadcrumbs;
        }
      }
      cache_set(__FUNCTION__, $data, rp_breadcrumbs_CACHE_STORAGE);
    }
  }

  return isset($data[$pattern_needle]) ? $data[$pattern_needle] : array();
}

/**
 * Create sql pattern from url.
 * Replaces all path arguments except the 1st one with %-symbol.
 *
 * @param string $path
 * @return string pattern
 */
function rp_breadcrumbs_path_pattern($path) {
  $cache = &drupal_static(__FUNCTION__);
  if (empty($cache[$path])) {
    // Example: 'node/%node/view' -> 'node/%/%.
    $cache[$path] = preg_replace("
            /\/     # start with slash
            [^\/]+  # all symbols except for the slash
            /x", '/%', $path);
  }
  return $cache[$path];
}

/**
 * This is version of drupal_sort_weight() for objects.
 * Function used by uasort to sort array of objects by weight.
 *
 * @param $a
 * @param $b
 * @return int
 */
function _rp_breadcrumbs_sort_weight($a, $b) {
  $a_weight = isset($a->weight) ? $a->weight : 0;
  $b_weight = isset($b->weight) ? $b->weight : 0;
  if ($a_weight == $b_weight) {
    return 0;
  }
  return ($a_weight < $b_weight) ? -1 : 1;
}

/**
 * Helper function to clean URLs according to Path Breadcrumbs settings.
 *
 * @param $url URL to clean.
 * @param &$options array of options for l() function.
 *   Function can overwrite 'query' and 'fragment' keys with data from $url.
 * @param $method One of supported methods: 'none', 'ctools', 'pathauto'.
 *
 * @return string Cleared URL.
 */
function _rp_breadcrumbs_clean_url($url, &$options, $method = NULL) {
  // Reset options.
  $options['fragment'] = '';
  $options['query'] = array();

  // Decode &amp; back to &.
  $url_short = htmlspecialchars_decode($url, ENT_NOQUOTES);
  $url_parts = parse_url($url_short);

  // Remove #hash from URL.
  if (!empty($url_parts['fragment'])) {
    $options['fragment'] = $url_parts['fragment'];
    list($url_short, ) = explode('#', $url_short, 2);
  }
  // Remove query string from URL.
  $options['query'] = array();
  if (!empty($url_parts['query'])) {
    list($url_short, ) = explode('?', $url_short, 2);
    parse_str($url_parts['query'], $query);
    $options['query'] += $query;
  }

  if (empty($method)) {
    $method = variable_get('rp_breadcrumbs_url_cleaning_method', 'none');
  }
  if ($method == 'none') {
    return $url_short;
  }

  // Ignore absolute URLs.
  if (preg_match('@^http(s?)://@i', $url_short)) {
    return $url_short;
  }

  $ctools_cleanstring_settings = array(
    'clean id' => 'rp_breadcrumbs_url',
    'lower case' => TRUE,
    'transliterate' => TRUE,
    'reduce ascii' => FALSE,
    'separator' => '-',
  );

  $pieces = explode('/', $url_short);
  $results = array();

  if ($method == 'ctools') {
    ctools_include('cleanstring');

    foreach ($pieces as $piece) {
      $results[] = ctools_cleanstring($piece, $ctools_cleanstring_settings);
    }
    $options['fragment'] = ctools_cleanstring($options['fragment'], $ctools_cleanstring_settings);

  }
  elseif ($method == 'pathauto' && module_exists('pathauto')) {
    module_load_include('inc', 'pathauto');

    foreach ($pieces as $piece) {
      $results[] = pathauto_cleanstring($piece);
    }
    $options['fragment'] = pathauto_cleanstring($options['fragment']);

  }
  else {
    $results = $pieces;
  }

  return implode('/', $results);
}
