<?php

$plugin = array(
    'title' => t('Header and Two Columns 1/3 + 2/3'),
    'category' => t('Republish layouts'),
    'icon' => 'head_two_col_33_66.png',
    'theme' => 'head_two_col_33_66',
    'css' => 'head_two_col_33_66.css',
    'regions' => array(
        'header' => t('Header'),
        'main_right' => t('Main-Right'),
        'main_left' => t('Main-Left'),
        'footer' => t('Footer'),
    ),
);