<?php

$plugin = array(
  'title' => t('Front'),
  'category' => t('Republish layouts'),
  'icon' => 'front.png',
  'theme' => 'front',
  'css' => 'front.css',
  'regions' => array(
    'banner' => t('Banner'),
    'header' => t('Header'),
    'top_second' => t('Top-Second'),
    'top_third' => t('Top-Third'),
    'top_right' => t('Top-Right'),
    'top_left' => t('Top-Left'),
    'middle' => t('Middle'),
    'middle_first' => t('Middle-First'),
    'middle_second' => t('Middle-Second'),
    'middle_left' => t('Middle-left'),
    'middle_right' => t('Middle-right'),
    'bottom' => t('Bottom'),
    'footer' => t('Footer'),
  ),
);
