<?php

$plugin = array(
  'title' => t('Three columns stacked'),
  'category' => t('Republish layouts'),
  'icon' => 'threecol_stacked.png',
  'theme' => 'threecol_stacked',
  'css' => 'threecol_stacked.css',
  'regions' => array(
    'banner' => t('Banner'),
    'header' => t('Header'),
    'top_first' => t('Top-First'),
    'top_second' => t('Top-Second'),
    'top_third' => t('Top-Third'),
    'top_right' => t('Top-Right'),
    'top_left' => t('Top-Left'),
    'middle' => t('Middle'),
    'middle_first' => t('Middle-First'),
    'middle_second' => t('Middle-Second'),
    'bottom' => t('Bottom'),
    'footer' => t('Footer'),
  ),
);
